# Generated by Django 5.1.3 on 2024-11-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('average_rating', models.FloatField()),
                ('session_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-average_rating'],
            },
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('requesters', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('topic', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-frequency'],
                'indexes': [models.Index(fields=['start_time'], name='training_an_start_t_80b9a6_idx'), models.Index(fields=['topic'], name='training_an_topic_c6f65d_idx'), models.Index(fields=['industry'], name='training_an_industr_ad4fe7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('metric', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('count', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='training_an_categor_6f6a66_idx'), models.Index(fields=['metric'], name='training_an_metric_0555bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=100)),
                ('participants', models.IntegerField()),
                ('experience', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='training_an_date_429dfb_idx'), models.Index(fields=['topic'], name='training_an_topic_f5d14a_idx'), models.Index(fields=['industry'], name='training_an_industr_118e57_idx'), models.Index(fields=['state'], name='training_an_state_baf95b_idx')],
            },
        ),
    ]
