# Generated by Django 5.1.3 on 2024-11-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='requesters',
            field=models.TextField(blank=True),
        ),
    ]
