# Generated by Django 5.1.3 on 2024-11-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_analytics', '0002_alter_resourcerequest_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
