# Generated by Django 5.1.3 on 2024-11-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_analytics', '0003_alter_resourcerequest_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingAnalytics',
        ),
        migrations.DeleteModel(
            name='TrainingSession',
        ),
    ]
