# Generated by Django 5.1.3 on 2024-11-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_analytics', '0004_delete_traininganalytics_delete_trainingsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicrating',
            name='session_count',
        ),
    ]
