# Generated by Django 5.1.3 on 2024-11-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_analytics', '0006_topicrating_session_count'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resourcerequest',
            name='training_an_start_t_80b9a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='resourcerequest',
            name='training_an_topic_c6f65d_idx',
        ),
        migrations.RemoveIndex(
            model_name='resourcerequest',
            name='training_an_industr_ad4fe7_idx',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='county',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='state',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='topic',
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['resource'], name='training_an_resourc_371136_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['frequency'], name='training_an_frequen_706027_idx'),
        ),
    ]
