# Generated by Django 5.1.3 on 2024-11-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_analytics', '0008_dailyattendance_industryparticipation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicfrequency',
            options={'ordering': ['-frequency']},
        ),
    ]
