# Generated by Django 5.1.3 on 2024-11-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_analytics', '0009_alter_topicfrequency_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('strategic_insights', models.TextField()),
                ('opportunities', models.TextField()),
                ('predictions', models.TextField()),
            ],
        ),
    ]
